import dayjs from 'dayjs/esm';

import { ICellModelCosmos, NewCellModelCosmos } from './cell-model-cosmos.model';

export const sampleWithRequiredData: ICellModelCosmos = {
  id: '029bde0d-fa20-4f15-9227-973bbe9a9f9e',
  species: 'Missouri and Cove',
  targetOrgan: 'Chips viral Refined',
  targetTissue: 'Handmade',
  vesselInfo: 'vertical services',
  ratingCharacterization: 50167,
  ratingComplexity: 14714,
  ratingModelCost: 73915,
  ratingThroughPutCapacity: 40517,
  ratingTurnAroundTime: 40006,
  department: 'well-modulated Regional',
  modelState: 'Towels',
  applicationADME: false,
  applicationEfficacy: true,
  applicationNone: false,
  applicationSafety: true,
  isRegulatorySubmission: false,
};

export const sampleWithPartialData: ICellModelCosmos = {
  id: '870e41b7-60d1-45dd-8a8a-65a9218d193b',
  species: 'Future',
  targetOrgan: 'Developer transparent synthesizing',
  targetTissue: 'Music',
  vesselInfo: 'killer implement Manager',
  vesselType: 'Rustic Agent scalable',
  inhouse: false,
  ratingCharacterization: 97062,
  ratingComplexity: 5323,
  ratingModelCost: 80727,
  ratingThroughPutCapacity: 31394,
  ratingTurnAroundTime: 28654,
  department: 'static',
  modelState: 'program utilize Checking',
  applicationADME: false,
  applicationEfficacy: false,
  applicationNone: true,
  applicationSafety: false,
  animalAssayReplaced: 'Assimilated Soap programming',
  isRegulatorySubmission: false,
  publications: 'action-items Credit Cambridgeshire',
};

export const sampleWithFullData: ICellModelCosmos = {
  id: 'd43933f0-ea3b-4726-bd46-8a4eee34b72d',
  name: 'Analyst Handmade Directives',
  dateAdded: dayjs('2022-12-08T23:24'),
  dateUpdated: dayjs('2022-12-09T04:55'),
  species: 'human-resource Avon Tuna',
  targetOrgan: 'Berkshire Romania Future',
  targetTissue: 'capacitor',
  vesselInfo: 'Reactive Concrete',
  matrix: false,
  protocol: 'Lakes markets Antilles',
  manufacturer: 'Senior Wooden',
  matrixType: 'Wallis Plastic',
  vesselType: 'Auto Mobility multimedia',
  inhouse: false,
  characterizationData: 'Associate Unbranded THX',
  ratingCharacterization: 37445,
  ratingComplexity: 80078,
  ratingModelCost: 3641,
  ratingThroughPutCapacity: 78618,
  ratingTurnAroundTime: 67520,
  imageUrl: 'magenta Internal',
  department: 'solution-oriented Chips',
  modelState: 'Lodge Tools',
  applicationADME: true,
  applicationEfficacy: false,
  applicationNone: true,
  applicationSafety: false,
  animalAssayReplaced: 'redundant Clothing',
  comment: 'Bulgarian deposit driver',
  experts: 'Sum Electronics Rustic',
  link: 'Unbranded',
  isRegulatorySubmission: false,
  publications: 'Paradigm International',
  limitationPercieved: 'Avon Harbor Implementation',
};

export const sampleWithNewData: NewCellModelCosmos = {
  species: 'Jewelery enterprise',
  targetOrgan: 'Grove Future Nuevo',
  targetTissue: 'Intelligent Internal AGP',
  vesselInfo: 'United Shoes invoice',
  ratingCharacterization: 4903,
  ratingComplexity: 78735,
  ratingModelCost: 52832,
  ratingThroughPutCapacity: 70868,
  ratingTurnAroundTime: 70683,
  department: 'Namibia online Chicken',
  modelState: 'CSS',
  applicationADME: true,
  applicationEfficacy: false,
  applicationNone: true,
  applicationSafety: false,
  isRegulatorySubmission: true,
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
